apiVersion: v1
kind: Service
metadata:
  name: insuretech-test-app-service
  labels:
    app: insuretech-test-app
spec:
  selector:
    app: insuretech-test-app
  ports:
    - protocol: TCP
      port: 8080 # Порт, по которому сервис будет доступен
      targetPort: 8080 # Порт, на котором приложение слушает внутри пода
  type: ClusterIP # Используем ClusterIP, доступ будет через `minikube service --url`